name: CI

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v6@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v6@e279bb959325dab635dd2c09392533439d90093
        with:
          version: 11

      - name: "⚡ Setup Node.js"
        uses: actions/setup-node@v6@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm install

      - name: "🎭 Install Playwright browsers"
        run: pnpm exec playwright install --with-deps chromium

      - name: "🔎 Lint code"
        run: pnpm run lint

      - name: "📝 Checking code format"
        run: pnpm run format:check

      - name: "🚀 Build the project"
        run: pnpm run build

      - name: "🧪 Run tests"
        run: pnpm run test:all
